# working on Real Project with Python

(A part of big data analysis)

# THE WEATHER DATA SET

Here, The weather Dataset is a time-series data set with per-hour information about the weather conditions at a particular location. It records temperature, dew point temperature, Relative Humidity,Wind speed,visibility, pressure and conditions.

The data is available as a csv file. We are going to analyze the data set using the pandas data Frame.

In [3]:
import pandas as pd

In [59]:
data=pd.read_csv(r"C:\Users\Sonu\Desktop\data science project\csv file\weatherHistory.csv")

In [60]:
data

,Formatted Date,Summary,Precip Type,Temperature (C),Apparent Temperature (C),Humidity,Wind Speed (km/h),Wind Bearing (degrees),Visibility (km),Loud Cover,Pressure (millibars),weather
0,2006-04-01 00:00:00.000 +0200,Partly Cloudy,rain,9.472222,7.388889,0.89,14.1197,251,15.8263,0,1015.13,Partly cloudy throughout the day.
1,2006-04-01 01:00:00.000 +0200,Partly Cloudy,rain,9.355556,7.227778,0.86,14.2646,259,15.8263,0,1015.63,Partly cloudy throughout the day.
2,2006-04-01 02:00:00.000 +0200,Mostly Cloudy,rain,9.377778,9.377778,0.89,3.9284,204,14.9569,0,1015.94,Partly cloudy throughout the day.
3,2006-04-01 03:00:00.000 +0200,Partly Cloudy,rain,8.288889,5.944444,0.83,14.1036,269,15.8263,0,1016.41,Partly cloudy throughout the day.
4,2006-04-01 04:00:00.000 +0200,Mostly Cloudy,rain,8.755556,6.977778,0.83,11.0446,259,15.8263,0,1016.51,Partly cloudy throughout the day.
...,...,...,...,...,...,...,...,...,...,...,...,...
96448,2016-09-09 19:00:00.000 +0200,Partly Cloudy,rain,26.016667,26.016667,0.43,10.9963,31,16.1000,0,1014.36,Partly cloudy starting in the morning.
96449,2016-09-09 20:00:00.000 +0200,Partly Cloudy,rain,24.583333,24.583333,0.48,10.0947,20,15.5526,0,1015.16,Partly cloudy starting in the morning.
96450,2016-09-09 21:00:00.000 +0200,Partly Cloudy,rain,22.038889,22.038889,0.56,8.9838,30,16.1000,0,1015.66,Partly cloudy starting in the morning.
96451,2016-09-09 22:00:00.000 +0200,Partly Cloudy,rain,21.522222,21.522222,0.60,10.5294,20,16.1000,0,1015.95,Partly cloudy starting in the morning.
96452,2016-09-09 23:00:00.000 +0200,Partly Cloudy,rain,20.438889,20.438889,0.61,5.8765,39,15.5204,0,1016.16,Partly cloudy starting in the morning.

# How to analyze Dataframe
# .head()

# it show the first five rows in the data

In [6]:
data.head()

,Formatted Date,Summary,Precip Type,Temperature (C),Apparent Temperature (C),Humidity,Wind Speed (km/h),Wind Bearing (degrees),Visibility (km),Loud Cover,Pressure (millibars),weather
0,2006-04-01 00:00:00.000 +0200,Partly Cloudy,rain,9.472222,7.388889,0.89,14.1197,251,15.8263,0,1015.13,Partly cloudy throughout the day.
1,2006-04-01 01:00:00.000 +0200,Partly Cloudy,rain,9.355556,7.227778,0.86,14.2646,259,15.8263,0,1015.63,Partly cloudy throughout the day.
2,2006-04-01 02:00:00.000 +0200,Mostly Cloudy,rain,9.377778,9.377778,0.89,3.9284,204,14.9569,0,1015.94,Partly cloudy throughout the day.
3,2006-04-01 03:00:00.000 +0200,Partly Cloudy,rain,8.288889,5.944444,0.83,14.1036,269,15.8263,0,1016.41,Partly cloudy throughout the day.
4,2006-04-01 04:00:00.000 +0200,Mostly Cloudy,rain,8.755556,6.977778,0.83,11.0446,259,15.8263,0,1016.51,Partly cloudy throughout the day.

# .Shape()
# it shows the total no. of rows and column of the dataframe

In [34]:
data.shape

(96453, 12)

# .index
# the attribute provides the index of the dataframe

In [35]:
data.index

RangeIndex(start=0, stop=96453, step=1)

# .Columns
# It shows the name of each column

In [36]:
data.columns

Index(['Formatted Date', 'Summary', 'Precip Type', 'Temperature (C)',
       'Apparent Temperature (C)', 'Humidity', 'Wind Speed (km/h)',
       'Wind Bearing (degrees)', 'Visibility (km)', 'Loud Cover',
       'Pressure (millibars)', 'weather'],
      dtype='object')

# .dtypes
# it shows the data -type of each column

In [2]:
data.dtypes

NameError: name 'data' is not defined

# .unique()
# In a column, it shows all the unique values, it can be applied on a single column only, not on the whole dataframe.

In [38]:
data['Visibility (km)'].unique()

array([1.58263e+01, 1.49569e+01, 9.98200e+00, 1.12056e+01, 1.14471e+01,
       1.12700e+01, 1.10285e+01, 6.19850e+00, 8.05000e+00, 1.03523e+01,
       6.69760e+00, 9.90150e+00, 5.97310e+00, 1.08031e+01, 1.06743e+01,
       1.08192e+01, 1.07548e+01, 1.08997e+01, 1.08514e+01, 1.10768e+01,
       1.08836e+01, 7.61530e+00, 2.65650e+00, 3.81570e+00, 4.49190e+00,
       4.44360e+00, 5.68330e+00, 3.10730e+00, 3.20390e+00, 1.40553e+01,
       6.11800e+00, 6.16630e+00, 7.96950e+00, 6.34340e+00, 1.05455e+01,
       1.49086e+01, 1.50052e+01, 1.58746e+01, 1.00464e+01, 1.00303e+01,
       1.19784e+01, 1.41680e+01, 5.92480e+00, 1.22360e+00, 7.21280e+00,
       1.11251e+01, 1.33791e+01, 1.13988e+01, 1.12861e+01, 1.56975e+01,
       1.48764e+01, 6.84250e+00, 1.53594e+01, 4.29870e+00, 4.12160e+00,
       4.76560e+00, 2.93020e+00, 5.84430e+00, 9.61170e+00, 9.67610e+00,
       2.01250e+00, 5.21640e+00, 1.45866e+01, 1.56009e+01, 1.47154e+01,
       6.11800e-01, 3.63860e+00, 1.11090e+00, 5.15200e-01, 4.34700e-01,
       6.92300e-01, 2.20570e+00, 4.20210e+00, 6.31120e+00, 8.19490e+00,
       6.89080e+00, 7.27720e+00, 4.74950e+00, 5.82820e+00, 3.83180e+00,
       4.50800e+00, 3.12340e+00, 1.80320e+00, 3.88010e+00, 3.86400e+00,
       3.25220e+00, 6.44000e-01, 1.25580e+00, 2.35060e+00, 4.02500e+00,
       6.26290e+00, 9.62780e+00, 8.13050e+00, 1.06260e+00, 1.78710e+00,
       3.36490e+00, 4.45970e+00, 1.91590e+00, 1.75490e+00, 2.36670e+00,
       2.89800e-01, 2.55990e+00, 6.29510e+00, 1.11412e+01, 1.48120e+01,
       9.80490e+00, 2.02860e+00, 1.73880e+00, 7.88900e-01, 9.54730e+00,
       4.28260e+00, 7.40600e-01, 8.33980e+00, 1.40875e+01, 1.54721e+01,
       1.09802e+01, 1.04006e+01, 1.19301e+01, 1.20428e+01, 1.52628e+01,
       1.18979e+01, 1.16886e+01, 9.75660e+00, 9.43460e+00, 1.46349e+01,
       1.16725e+01, 9.69220e+00, 4.66900e-01, 5.39350e+00, 9.53120e+00,
       1.53111e+01, 3.44540e+00, 1.09480e+01, 1.00625e+01, 2.73700e+00,
       1.57297e+01, 3.97670e+00, 3.67080e+00, 3.75130e+00, 7.14840e+00,
       7.90510e+00, 9.94980e+00, 1.04167e+01, 7.37380e+00, 1.10446e+01,
       9.01600e+00, 1.39104e+01, 1.56492e+01, 1.47315e+01, 1.36528e+01,
       4.58850e+00, 5.87650e+00, 1.12539e+01, 5.03930e+00, 6.98740e+00,
       1.40231e+01, 1.02718e+01, 1.38943e+01, 9.70830e+00, 9.98200e-01,
       9.85320e+00, 1.54399e+01, 1.42324e+01, 3.91230e+00, 1.55526e+01,
       7.82460e+00, 4.94270e+00, 6.93910e+00, 1.04811e+01, 6.53660e+00,
       1.36850e+01, 6.06970e+00, 6.58490e+00, 4.99100e+00, 1.60517e+01,
       7.13230e+00, 9.83710e+00, 1.39426e+01, 1.61000e+01, 1.13183e+01,
       6.02140e+00, 4.62070e+00, 1.47637e+01, 1.07870e+01, 3.49370e+00,
       1.01913e+01, 8.30760e+00, 1.47959e+01, 7.87290e+00, 1.04489e+01,
       7.98560e+00, 8.00170e+00, 1.05294e+01, 1.07226e+01, 1.37333e+01,
       8.42030e+00, 8.11440e+00, 1.17047e+01, 7.03570e+00, 4.39530e+00,
       4.34700e+00, 4.33090e+00, 2.89800e+00, 1.89980e+00, 4.18600e-01,
       2.97850e+00, 5.32910e+00, 4.84610e+00, 4.83000e+00, 4.00890e+00,
       3.94450e+00, 3.30050e+00, 1.18496e+01, 9.48290e+00, 1.70660e+00,
       1.36850e+00, 6.72980e+00, 1.62610e+00, 3.01070e+00, 4.91050e+00,
       5.76380e+00, 7.56700e-01, 3.22000e-01, 1.61000e-01, 6.60100e-01,
       2.73700e-01, 2.09300e-01, 9.33800e-01, 9.66000e-01, 1.30410e+00,
       1.81930e+00, 2.57600e+00, 2.44720e+00, 1.72270e+00, 1.88370e+00,
       4.83000e-01, 3.05900e-01, 1.77100e-01, 6.27900e-01, 7.08400e-01,
       2.60820e+00, 2.54380e+00, 1.32020e+00, 8.53300e-01, 4.02500e-01,
       2.41500e-01, 1.93200e-01, 1.61000e-02, 6.76200e-01, 5.47400e-01,
       0.00000e+00, 4.83000e-02, 3.22000e-02, 3.38100e-01, 8.05000e-01,
       7.24500e-01, 1.64220e+00, 1.12700e-01, 1.27190e+00, 1.41680e+00,
       8.85500e-01, 1.28800e+00, 1.44900e+00, 2.52770e+00, 2.83360e+00,
       1.06582e+01, 1.57780e+00, 3.41320e+00, 3.92840e+00, 5.52230e+00,
       4.87830e+00, 4.26650e+00, 6.00530e+00, 6.24680e+00, 6.48830e+00,
       1.38138e+01, 6.35950e+00, 5.13590e+00, 5.28080e+00, 1.15920e+00,
       6.05360e+00, 7.74410e+00, 5.40960e+00, 4.81390e+00, 1.02557e+01,
       1.94810e+00, 9.82100e-01, 8.46860e+00, 7.63140e+00, 3.39710e+00,
       3.13950e+00, 4.52410e+00, 7.72800e+00, 3.78350e+00, 4.31480e+00,
       4.37920e+00, 4.04110e+00, 3.55810e+00, 4.57240e+00, 7.51870e+00,
       8.61350e+00, 7.05180e+00, 1.56170e+00, 3.05900e+00, 5.69940e+00,
       6.03750e+00, 4.41140e+00, 1.93200e+00, 5.66720e+00, 6.18240e+00,
       1.77100e+00, 2.15740e+00, 2.62430e+00, 3.50980e+00, 5.47400e+00,
       8.75840e+00, 1.39748e+01, 1.15276e+01, 8.17880e+00, 6.77810e+00,
       4.07330e+00, 8.96770e+00, 1.51501e+01, 1.42163e+01, 1.20911e+01,
       1.45222e+01, 8.14660e+00, 1.38460e+00, 3.86400e-01, 1.85150e+00,
       1.86760e+00, 2.59210e+00, 1.51340e+00, 3.09120e+00, 3.96060e+00,
       5.57060e+00, 3.42930e+00, 3.33270e+00, 1.25902e+01, 8.05000e-02,
       1.59390e+00, 5.89260e+00, 7.18060e+00, 9.11260e+00, 2.96240e+00,
       5.81210e+00, 4.89440e+00, 4.95880e+00, 5.79600e+00, 5.50620e+00,
       2.72090e+00, 7.69580e+00, 9.56340e+00, 5.60280e+00, 4.36310e+00,
       4.73340e+00, 5.95700e+00, 1.49730e+00, 1.35240e+00, 2.14130e+00,
       5.11980e+00, 1.36206e+01, 7.64750e+00, 1.46510e+00, 1.65830e+00,
       2.86580e+00, 4.08940e+00, 4.42750e+00, 4.18600e+00, 2.88190e+00,
       8.32370e+00, 1.23970e+00, 1.17530e+00, 2.46330e+00, 7.06790e+00,
       1.27190e+01, 9.78880e+00, 8.09830e+00, 9.57950e+00, 9.27360e+00,
       7.77630e+00, 9.64390e+00, 8.54910e+00, 7.71190e+00, 6.79420e+00,
       6.82640e+00, 6.85860e+00, 8.22710e+00, 1.15759e+01, 6.90690e+00,
       7.35770e+00, 3.89620e+00, 3.52590e+00, 5.65110e+00, 8.74230e+00,
       4.68510e+00, 4.79780e+00, 3.84790e+00, 1.14310e+00, 8.37200e-01,
       9.17700e-01, 9.01600e-01, 9.49900e-01, 5.53840e+00, 5.73160e+00,
       6.13410e+00, 1.44095e+01, 9.45070e+00, 6.64930e+00, 9.82100e+00,
       1.05938e+01, 3.71910e+00, 6.87470e+00, 1.44900e-01, 3.46150e+00,
       4.05720e+00, 9.59560e+00, 1.83540e+00, 2.75310e+00, 3.34880e+00,
       3.18780e+00, 3.04290e+00, 1.43612e+01, 7.72800e-01, 5.63500e-01,
       4.78170e+00, 1.07709e+01, 1.46832e+01, 1.01108e+01, 9.74050e+00,
       2.99460e+00, 3.07510e+00, 3.17170e+00, 1.61000e+00, 8.21100e-01,
       3.15560e+00, 4.15380e+00, 6.47220e+00, 1.46027e+01, 4.50800e-01,
       1.29605e+01, 1.04972e+01, 7.00350e+00, 1.11895e+01, 3.47760e+00,
       6.23070e+00, 5.10370e+00, 7.80850e+00, 1.07387e+01, 8.08220e+00,
       1.44739e+01, 5.90870e+00, 1.10607e+01, 9.19310e+00, 9.32190e+00,
       4.71730e+00, 3.65470e+00, 3.57420e+00, 5.31300e+00, 2.10910e+00,
       1.05777e+01, 7.26110e+00, 1.55365e+01, 2.07690e+00, 2.17350e+00,
       1.28961e+01, 1.53755e+01, 1.09480e+00, 4.23430e+00, 2.12520e+00,
       3.62250e+00, 1.09158e+01, 4.60460e+00, 6.40780e+00, 7.11620e+00,
       7.08400e+00, 6.08580e+00, 3.76740e+00, 4.92660e+00, 2.30230e+00,
       6.74590e+00, 5.07150e+00, 5.08760e+00, 2.38280e+00, 2.49550e+00,
       2.94630e+00, 2.33450e+00, 5.86040e+00, 7.55090e+00, 7.66360e+00,
       8.64570e+00, 1.54560e+00, 9.41850e+00, 9.86930e+00, 5.26470e+00,
       5.23250e+00, 9.14480e+00, 5.34520e+00, 4.47580e+00, 8.91940e+00,
       9.49900e+00, 1.12378e+01, 8.71010e+00, 5.24860e+00, 1.16081e+01,
       8.93550e+00, 1.18013e+01, 1.29283e+01, 1.41036e+01, 9.40240e+00,
       1.03684e+01, 1.08353e+01, 4.21820e+00, 9.51510e+00, 1.17530e+01,
       7.88900e+00, 9.28970e+00, 9.93370e+00, 7.59920e+00, 3.28440e+00,
       3.26830e+00, 5.18420e+00, 2.47940e+00, 3.60640e+00, 2.68870e+00,
       4.66900e+00, 5.74770e+00, 3.23610e+00, 3.22000e+00, 1.01430e+00,
       1.15920e+01, 1.24292e+01, 1.09641e+01, 8.35590e+00, 1.44256e+01,
       1.03845e+01, 1.11573e+01, 1.02074e+01, 1.52467e+01, 8.25930e+00,
       1.45705e+01, 1.48442e+01, 1.13505e+01, 3.70300e+00, 1.44578e+01,
       2.31840e+00, 2.06080e+00, 1.33147e+01, 8.62960e+00, 5.42570e+00,
       7.53480e+00, 5.44180e+00, 7.42210e+00, 6.15020e+00, 2.41500e+00,
       9.37020e+00, 3.54200e-01, 2.81750e+00, 4.70120e+00, 4.55630e+00,
       1.00947e+01, 8.90330e+00, 7.29330e+00, 2.64040e+00, 1.06421e+01,
       8.51690e+00, 9.38630e+00, 9.24140e+00, 1.10929e+01, 5.16810e+00,
       7.16450e+00, 8.01780e+00, 2.91410e+00, 1.43290e+00, 7.93730e+00,
       5.95700e-01, 2.27010e+00, 7.45430e+00, 1.44900e+01, 8.85500e+00,
       1.01752e+01, 1.55043e+01, 1.54560e+01, 1.54238e+01, 5.02320e+00,
       9.66000e+00, 4.25040e+00, 1.34435e+01, 1.34757e+01, 1.07065e+01,
       1.04650e+00, 1.43451e+01, 1.15437e+01, 1.55204e+01, 4.54020e+00,
       1.14954e+01, 1.51179e+01, 1.56653e+01, 1.50535e+01, 9.17700e+00,
       5.77990e+00, 7.79240e+00, 9.06430e+00, 6.60100e+00, 6.52050e+00,
       6.10190e+00, 6.45610e+00, 7.30940e+00, 2.18960e+00, 2.84970e+00,
       9.12870e+00, 7.67970e+00, 1.40070e+00, 7.40600e+00, 1.69050e+00,
       3.59030e+00, 3.54200e+00, 5.58670e+00, 5.31300e-01, 1.52950e+00,
       1.30893e+01, 1.98030e+00, 1.39587e+01, 1.19140e+01, 8.06610e+00,
       9.35410e+00, 9.33800e+00, 1.16403e+01, 1.03040e+01, 7.01960e+00,
       1.35401e+01, 1.53916e+01, 1.54077e+01, 1.43290e+01, 3.73520e+00,
       6.21460e+00, 4.16990e+00, 8.16270e+00, 5.15200e+00, 7.56700e+00,
       9.20920e+00, 9.09650e+00, 6.61710e+00, 1.67440e+00, 1.56814e+01,
       1.43934e+01, 1.15115e+01, 1.21877e+01, 1.49730e+01, 1.57136e+01,
       1.52789e+01, 1.59068e+01, 8.82280e+00, 2.28620e+00, 5.20030e+00,
       1.32664e+01, 7.38990e+00, 1.12700e+00, 2.22180e+00, 1.13827e+01,
       6.63320e+00, 2.04470e+00, 3.70300e-01, 4.99100e-01, 2.09300e+00,
       5.36130e+00, 1.96420e+00, 2.78530e+00, 2.23790e+00, 2.67260e+00,
       3.79960e+00, 2.80140e+00, 2.51160e+00, 5.45790e+00, 3.99280e+00,
       2.70480e+00, 3.02680e+00, 5.98920e+00, 2.76920e+00, 1.48120e+00,
       1.13666e+01, 7.19670e+00, 7.95340e+00, 7.48650e+00, 2.25400e+00,
       1.38621e+01, 9.16090e+00, 1.01591e+01, 9.66000e-02, 7.32550e+00,
       5.61890e+00, 9.99810e+00, 1.01430e+01, 6.92300e+00, 1.14149e+01,
       8.87110e+00, 1.44417e+01, 5.29690e+00, 2.43110e+00, 1.22682e+01,
       1.24775e+01, 8.67790e+00, 9.46680e+00, 1.17369e+01, 1.03362e+01,
       4.63680e+00, 4.13770e+00, 5.00710e+00, 9.77270e+00, 7.43820e+00,
       5.55450e+00, 1.46671e+01, 1.45383e+01, 7.34160e+00, 4.86220e+00,
       6.66540e+00, 1.99640e+00, 8.88720e+00, 9.25750e+00, 8.59740e+00,
       1.02396e+01, 1.33630e+01, 1.35240e+01, 1.41841e+01, 2.25400e-01,
       7.85680e+00, 5.63500e+00, 1.42807e+01, 1.39265e+01, 1.16242e+01,
       1.06904e+01, 6.95520e+00, 2.57600e-01, 1.20750e+00, 9.72440e+00,
       8.83890e+00, 6.97130e+00, 1.54882e+01, 1.14632e+01, 1.11734e+01,
       9.30580e+00, 4.10550e+00, 1.55687e+01, 1.21555e+01, 1.22843e+01,
       1.25097e+01, 1.26063e+01, 1.37494e+01, 1.38460e+01, 9.88540e+00,
       8.77450e+00, 1.58424e+01, 6.71370e+00, 8.37200e+00, 1.47798e+01,
       4.65290e+00, 3.68690e+00, 1.19140e+00, 1.32503e+01, 1.28478e+01,
       7.58310e+00, 8.03390e+00, 1.10124e+01, 6.50440e+00, 1.31537e+01,
       1.13022e+01, 8.66180e+00, 1.07870e+00, 1.46510e+01, 7.50260e+00,
       1.37816e+01, 5.79600e-01, 1.51340e+01, 1.27029e+01, 1.26868e+01,
       1.18818e+01, 1.13344e+01, 1.36367e+01, 1.02235e+01, 8.69400e+00,
       1.20106e+01, 1.51823e+01, 1.20750e+01, 1.31376e+01, 1.32342e+01,
       7.92120e+00, 1.19945e+01, 1.31698e+01, 6.44000e-02, 1.05616e+01,
       1.09319e+01, 7.84070e+00, 8.58130e+00, 9.08040e+00, 1.33630e+00,
       1.04650e+01, 3.31660e+00, 9.04820e+00, 1.15598e+01, 1.02879e+01,
       1.05133e+01, 7.10010e+00, 1.21233e+01, 1.38299e+01, 1.00142e+01,
       7.22890e+00, 6.76200e+00, 1.34113e+01, 8.79060e+00, 1.29927e+01,
       8.99990e+00, 1.03040e+00, 1.46188e+01, 1.42968e+01, 1.03201e+01,
       1.30088e+01, 8.72620e+00, 5.49010e+00, 1.18335e+01, 1.42002e+01,
       1.17852e+01, 1.11090e+01, 1.06099e+01, 6.39170e+00, 6.37560e+00,
       1.25580e+01, 1.41519e+01, 1.51662e+01, 1.22199e+01, 5.05540e+00,
       6.68150e+00, 6.81030e+00, 6.42390e+00, 5.37740e+00, 1.36689e+01,
       7.24500e+00, 1.43129e+01, 6.44000e+00, 6.32730e+00, 3.38100e+00,
       6.55270e+00, 1.38782e+01, 8.24320e+00, 1.24614e+01, 1.40714e+01,
       2.39890e+00, 1.35562e+01, 1.21394e+01, 1.52145e+01, 4.97490e+00,
       8.69400e-01, 1.34918e+01, 8.95160e+00, 9.03210e+00, 1.14310e+01,
       7.76020e+00, 1.00786e+01, 5.94090e+00, 8.38810e+00, 1.34274e+01,
       1.37977e+01, 6.27900e+00, 1.09963e+01, 1.31215e+01, 8.21100e+00,
       9.96590e+00, 1.04328e+01, 1.26707e+01, 1.46993e+01, 1.37655e+01,
       1.42485e+01, 8.43640e+00, 1.43773e+01, 1.30249e+01, 1.28317e+01,
       1.48603e+01, 1.32020e+01, 8.29150e+00, 1.59229e+01, 8.98380e+00,
       1.28800e-01, 1.22521e+01, 1.50213e+01, 1.28156e+01, 1.45061e+01,
       1.12217e+01, 1.57780e+01, 1.57941e+01, 1.53433e+01, 1.42646e+01,
       6.56880e+00, 1.48281e+01, 1.40392e+01, 1.41358e+01, 1.59551e+01,
       1.17691e+01, 1.49891e+01, 1.58585e+01, 1.51984e+01, 1.50857e+01,
       1.23809e+01, 1.19623e+01, 1.27673e+01, 1.21716e+01, 1.26385e+01,
       1.18174e+01, 1.30410e+01, 1.30732e+01, 1.40070e+01, 8.27540e+00,
       1.25741e+01, 1.56170e+01, 1.60195e+01, 1.45544e+01, 1.22360e+01,
       1.23970e+01, 8.56520e+00, 1.24936e+01, 1.25419e+01, 9.22530e+00,
       7.47040e+00, 1.31859e+01, 8.50080e+00, 1.35723e+01, 1.39909e+01,
       1.41197e+01, 1.34596e+01, 1.01269e+01, 8.45250e+00, 8.48470e+00,
       8.40420e+00, 8.53300e+00, 9.91760e+00, 5.71550e+00, 8.80670e+00,
       1.14793e+01, 1.06260e+01, 1.24131e+01, 1.08675e+01, 1.23326e+01,
       1.17208e+01, 1.52306e+01, 1.52950e+01, 1.53272e+01, 1.57619e+01,
       1.58102e+01, 1.59390e+01, 1.59873e+01, 1.60839e+01])

# .nunique()
# It shows the total no. of unique values in each column. it can be applied on a single column as well as on whole dataframe.

In [39]:
data.nunique()

Formatted Date              96429
Summary                        27
Precip Type                     2
Temperature (C)              7574
Apparent Temperature (C)     8984
Humidity                       90
Wind Speed (km/h)            2484
Wind Bearing (degrees)        360
Visibility (km)               949
Loud Cover                      1
Pressure (millibars)         4979
weather                       214
dtype: int64

# .count
# It shows the total no. of non-null values in each column.It can be applied on a single column as well as on whole dataframe.

In [40]:
data.count()

Formatted Date              96453
Summary                     96453
Precip Type                 95936
Temperature (C)             96453
Apparent Temperature (C)    96453
Humidity                    96453
Wind Speed (km/h)           96453
Wind Bearing (degrees)      96453
Visibility (km)             96453
Loud Cover                  96453
Pressure (millibars)        96453
weather                     96453
dtype: int64

# .value_counts
# In a column, it shows all the unique values with thier count. It can be applied on single column only.

In [41]:
data.columns

Index(['Formatted Date', 'Summary', 'Precip Type', 'Temperature (C)',
       'Apparent Temperature (C)', 'Humidity', 'Wind Speed (km/h)',
       'Wind Bearing (degrees)', 'Visibility (km)', 'Loud Cover',
       'Pressure (millibars)', 'weather'],
      dtype='object')

In [42]:
data['Precip Type'].value_counts

<bound method IndexOpsMixin.value_counts of 0        rain
1        rain
2        rain
3        rain
4        rain
         ...
96448    rain
96449    rain
96450    rain
96451    rain
96452    rain
Name: Precip Type, Length: 96453, dtype: object>

# .info()
# provies basic information about the dataframe

In [43]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 96453 entries, 0 to 96452
Data columns (total 12 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   Formatted Date            96453 non-null  object
 1   Summary                   96453 non-null  object
 2   Precip Type               95936 non-null  object
 3   Temperature (C)           96453 non-null  float64
 4   Apparent Temperature (C)  96453 non-null  float64
 5   Humidity                  96453 non-null  float64
 6   Wind Speed (km/h)         96453 non-null  float64
 7   Wind Bearing (degrees)    96453 non-null  int64
 8   Visibility (km)           96453 non-null  float64
 9   Loud Cover                96453 non-null  int64
 10  Pressure (millibars)      96453 non-null  float64
 11  weather                   96453 non-null  object
dtypes: float64(6), int64(2), object(4)
memory usage: 8.8+ MB

 # Qo.1 Find all the unique 'wind speed' value in the data.

In [44]:
data.head(2)

,Formatted Date,Summary,Precip Type,Temperature (C),Apparent Temperature (C),Humidity,Wind Speed (km/h),Wind Bearing (degrees),Visibility (km),Loud Cover,Pressure (millibars),weather
0,2006-04-01 00:00:00.000 +0200,Partly Cloudy,rain,9.472222,7.388889,0.89,14.1197,251,15.8263,0,1015.13,Partly cloudy throughout the day.
1,2006-04-01 01:00:00.000 +0200,Partly Cloudy,rain,9.355556,7.227778,0.86,14.2646,259,15.8263,0,1015.63,Partly cloudy throughout the day.

In [45]:
data['Wind Speed (km/h)'].nunique()

2484

In [46]:
data['Wind Speed (km/h)'].unique()

array([14.1197, 14.2646,  3.9284, ..., 37.0622, 35.5971, 30.751 ])

In [48]:
data.head(2)

,Formatted Date,Summary,Precip Type,Temperature (C),Apparent Temperature (C),Humidity,Wind Speed (km/h),Wind Bearing (degrees),Visibility (km),Loud Cover,Pressure (millibars),weather
0,2006-04-01 00:00:00.000 +0200,Partly Cloudy,rain,9.472222,7.388889,0.89,14.1197,251,15.8263,0,1015.13,Partly cloudy throughout the day.
1,2006-04-01 01:00:00.000 +0200,Partly Cloudy,rain,9.355556,7.227778,0.86,14.2646,259,15.8263,0,1015.63,Partly cloudy throughout the day.

# Qo.2 Find the number of times when the weather is 'Foggy in the evening.'

In [49]:
data.head(2)

,Formatted Date,Summary,Precip Type,Temperature (C),Apparent Temperature (C),Humidity,Wind Speed (km/h),Wind Bearing (degrees),Visibility (km),Loud Cover,Pressure (millibars),weather
0,2006-04-01 00:00:00.000 +0200,Partly Cloudy,rain,9.472222,7.388889,0.89,14.1197,251,15.8263,0,1015.13,Partly cloudy throughout the day.
1,2006-04-01 01:00:00.000 +0200,Partly Cloudy,rain,9.355556,7.227778,0.86,14.2646,259,15.8263,0,1015.63,Partly cloudy throughout the day.

In [53]:
#value_counts()
data.weather.value_counts()

Mostly cloudy throughout the day.                                                                       20085
Partly cloudy throughout the day.                                                                        9981
Partly cloudy until night.                                                                               6169
Partly cloudy starting in the morning.                                                                   5184
Foggy in the morning.                                                                                    4201
                                                                                                        ...
Overcast starting in the afternoon.                                                                        24
Partly cloudy starting overnight continuing until night and breezy in the afternoon.                       24
Breezy starting in the afternoon continuing until evening and foggy in the evening.                        24
Partly cloudy starting in the morning and breezy starting in the afternoon continuing until evening.       24
Foggy starting overnight continuing until morning and breezy in the afternoon.                             23
Name: weather, Length: 214, dtype: int64

In [55]:
#filtering
data[data.weather=='Foggy in the evening.']

,Formatted Date,Summary,Precip Type,Temperature (C),Apparent Temperature (C),Humidity,Wind Speed (km/h),Wind Bearing (degrees),Visibility (km),Loud Cover,Pressure (millibars),weather
48,2006-04-11 00:00:00.000 +0200,Overcast,rain,13.772222,13.772222,0.60,17.0982,160,15.8263,0,1007.36,Foggy in the evening.
49,2006-04-11 01:00:00.000 +0200,Overcast,rain,13.283333,13.283333,0.63,14.3612,160,15.8263,0,1007.26,Foggy in the evening.
50,2006-04-11 02:00:00.000 +0200,Overcast,rain,8.633333,5.466667,0.87,22.0409,32,6.6976,0,1005.10,Foggy in the evening.
51,2006-04-11 03:00:00.000 +0200,Overcast,rain,11.250000,11.250000,0.83,11.3344,152,15.8263,0,1007.01,Foggy in the evening.
52,2006-04-11 04:00:00.000 +0200,Overcast,rain,11.183333,11.183333,0.89,11.2056,180,9.9015,0,1006.73,Foggy in the evening.
...,...,...,...,...,...,...,...,...,...,...,...,...
81664,2015-02-04 19:00:00.000 +0100,Overcast,rain,1.111111,-1.283333,0.93,7.5831,20,3.7030,0,1010.25,Foggy in the evening.
81665,2015-02-04 20:00:00.000 +0100,Foggy,rain,1.133333,-1.316667,0.93,7.7602,352,2.9785,0,1011.37,Foggy in the evening.
81666,2015-02-04 21:00:00.000 +0100,Overcast,rain,1.644444,-1.555556,0.92,10.9319,341,3.4615,0,1012.25,Foggy in the evening.
81667,2015-02-04 22:00:00.000 +0100,Overcast,rain,1.566667,-1.544444,0.93,10.4811,358,4.0733,0,1012.65,Foggy in the evening.
81668,2015-02-04 23:00:00.000 +0100,Foggy,rain,1.622222,-2.166667,0.96,13.7333,0,1.4490,0,1012.97,Foggy in the evening.

In [56]:
#groupby()
data.groupby('weather').get_group('Foggy in the evening.')

,Formatted Date,Summary,Precip Type,Temperature (C),Apparent Temperature (C),Humidity,Wind Speed (km/h),Wind Bearing (degrees),Visibility (km),Loud Cover,Pressure (millibars),weather
48,2006-04-11 00:00:00.000 +0200,Overcast,rain,13.772222,13.772222,0.60,17.0982,160,15.8263,0,1007.36,Foggy in the evening.
49,2006-04-11 01:00:00.000 +0200,Overcast,rain,13.283333,13.283333,0.63,14.3612,160,15.8263,0,1007.26,Foggy in the evening.
50,2006-04-11 02:00:00.000 +0200,Overcast,rain,8.633333,5.466667,0.87,22.0409,32,6.6976,0,1005.10,Foggy in the evening.
51,2006-04-11 03:00:00.000 +0200,Overcast,rain,11.250000,11.250000,0.83,11.3344,152,15.8263,0,1007.01,Foggy in the evening.
52,2006-04-11 04:00:00.000 +0200,Overcast,rain,11.183333,11.183333,0.89,11.2056,180,9.9015,0,1006.73,Foggy in the evening.
...,...,...,...,...,...,...,...,...,...,...,...,...
81664,2015-02-04 19:00:00.000 +0100,Overcast,rain,1.111111,-1.283333,0.93,7.5831,20,3.7030,0,1010.25,Foggy in the evening.
81665,2015-02-04 20:00:00.000 +0100,Foggy,rain,1.133333,-1.316667,0.93,7.7602,352,2.9785,0,1011.37,Foggy in the evening.
81666,2015-02-04 21:00:00.000 +0100,Overcast,rain,1.644444,-1.555556,0.92,10.9319,341,3.4615,0,1012.25,Foggy in the evening.
81667,2015-02-04 22:00:00.000 +0100,Overcast,rain,1.566667,-1.544444,0.93,10.4811,358,4.0733,0,1012.65,Foggy in the evening.
81668,2015-02-04 23:00:00.000 +0100,Foggy,rain,1.622222,-2.166667,0.96,13.7333,0,1.4490,0,1012.97,Foggy in the evening.

# Qo.3 Find the number of times when 'wind speed was exactly 14.1197.

In [7]:
data.head(2)

,Formatted Date,Summary,Precip Type,Temperature (C),Apparent Temperature (C),Humidity,Wind Speed (km/h),Wind Bearing (degrees),Visibility (km),Loud Cover,Pressure (millibars),weather
0,2006-04-01 00:00:00.000 +0200,Partly Cloudy,rain,9.472222,7.388889,0.89,14.1197,251,15.8263,0,1015.13,Partly cloudy throughout the day.
1,2006-04-01 01:00:00.000 +0200,Partly Cloudy,rain,9.355556,7.227778,0.86,14.2646,259,15.8263,0,1015.63,Partly cloudy throughout the day.

In [16]:
data[data['Wind Speed (km/h)']==14.1197]

,Formatted Date,Summary,Precip Type,Temperature (C),Apparent Temperature (C),Humidity,Wind Speed (km/h),Wind Bearing (degrees),Visibility (km),Loud Cover,Pressure (millibars),weather
0,2006-04-01 00:00:00.000 +0200,Partly Cloudy,rain,9.472222,7.388889,0.89,14.1197,251,15.8263,0,1015.13,Partly cloudy throughout the day.
618,2006-04-05 18:00:00.000 +0200,Overcast,rain,14.950000,14.950000,0.51,14.1197,159,11.2056,0,1006.26,Foggy in the morning.
646,2006-04-06 22:00:00.000 +0200,Overcast,rain,4.977778,1.877778,0.93,14.1197,339,8.0500,0,1014.08,Overcast throughout the day.
1264,2006-08-03 16:00:00.000 +0200,Mostly Cloudy,rain,24.877778,24.877778,0.64,14.1197,79,11.2700,0,1004.12,Mostly cloudy throughout the day.
1885,2006-12-25 13:00:00.000 +0100,Mostly Cloudy,rain,3.811111,0.450000,0.86,14.1197,307,13.9748,0,1030.81,Foggy in the morning.
...,...,...,...,...,...,...,...,...,...,...,...,...
94761,2016-11-28 13:00:00.000 +0100,Mostly Cloudy,rain,6.233333,3.422222,0.80,14.1197,185,10.5777,0,1019.19,Mostly cloudy throughout the day.
94784,2016-11-29 12:00:00.000 +0100,Mostly Cloudy,rain,5.650000,2.700000,0.81,14.1197,181,8.2915,0,1019.51,Mostly cloudy throughout the day.
94785,2016-11-29 13:00:00.000 +0100,Mostly Cloudy,rain,6.072222,3.222222,0.80,14.1197,185,10.5133,0,1019.23,Mostly cloudy throughout the day.
94833,2016-11-30 13:00:00.000 +0100,Mostly Cloudy,rain,5.911111,3.027778,0.80,14.1197,185,10.4650,0,1019.27,Mostly cloudy throughout the day.
96371,2016-09-06 14:00:00.000 +0200,Mostly Cloudy,rain,20.966667,20.966667,0.63,14.1197,59,10.3523,0,1017.84,Mostly cloudy starting overnight.

# Qo. 4 Find out the null values in the data.

In [19]:
data.isnull().sum()

Formatted Date                0
Summary                       0
Precip Type                 517
Temperature (C)               0
Apparent Temperature (C)      0
Humidity                      0
Wind Speed (km/h)             0
Wind Bearing (degrees)        0
Visibility (km)               0
Loud Cover                    0
Pressure (millibars)          0
weather                       0
dtype: int64

In [20]:
data.notnull().sum()

Formatted Date              96453
Summary                     96453
Precip Type                 95936
Temperature (C)             96453
Apparent Temperature (C)    96453
Humidity                    96453
Wind Speed (km/h)           96453
Wind Bearing (degrees)      96453
Visibility (km)             96453
Loud Cover                  96453
Pressure (millibars)        96453
weather                     96453
dtype: int64

# Qo.5  Rename the column name 'weather' of the dataframe to 'weather condition'.

In [21]:
data.head(2)

,Formatted Date,Summary,Precip Type,Temperature (C),Apparent Temperature (C),Humidity,Wind Speed (km/h),Wind Bearing (degrees),Visibility (km),Loud Cover,Pressure (millibars),weather
0,2006-04-01 00:00:00.000 +0200,Partly Cloudy,rain,9.472222,7.388889,0.89,14.1197,251,15.8263,0,1015.13,Partly cloudy throughout the day.
1,2006-04-01 01:00:00.000 +0200,Partly Cloudy,rain,9.355556,7.227778,0.86,14.2646,259,15.8263,0,1015.63,Partly cloudy throughout the day.

In [23]:
data.rename(columns={'weather':'weather condition'})

,Formatted Date,Summary,Precip Type,Temperature (C),Apparent Temperature (C),Humidity,Wind Speed (km/h),Wind Bearing (degrees),Visibility (km),Loud Cover,Pressure (millibars),weather condition
0,2006-04-01 00:00:00.000 +0200,Partly Cloudy,rain,9.472222,7.388889,0.89,14.1197,251,15.8263,0,1015.13,Partly cloudy throughout the day.
1,2006-04-01 01:00:00.000 +0200,Partly Cloudy,rain,9.355556,7.227778,0.86,14.2646,259,15.8263,0,1015.63,Partly cloudy throughout the day.
2,2006-04-01 02:00:00.000 +0200,Mostly Cloudy,rain,9.377778,9.377778,0.89,3.9284,204,14.9569,0,1015.94,Partly cloudy throughout the day.
3,2006-04-01 03:00:00.000 +0200,Partly Cloudy,rain,8.288889,5.944444,0.83,14.1036,269,15.8263,0,1016.41,Partly cloudy throughout the day.
4,2006-04-01 04:00:00.000 +0200,Mostly Cloudy,rain,8.755556,6.977778,0.83,11.0446,259,15.8263,0,1016.51,Partly cloudy throughout the day.
...,...,...,...,...,...,...,...,...,...,...,...,...
96448,2016-09-09 19:00:00.000 +0200,Partly Cloudy,rain,26.016667,26.016667,0.43,10.9963,31,16.1000,0,1014.36,Partly cloudy starting in the morning.
96449,2016-09-09 20:00:00.000 +0200,Partly Cloudy,rain,24.583333,24.583333,0.48,10.0947,20,15.5526,0,1015.16,Partly cloudy starting in the morning.
96450,2016-09-09 21:00:00.000 +0200,Partly Cloudy,rain,22.038889,22.038889,0.56,8.9838,30,16.1000,0,1015.66,Partly cloudy starting in the morning.
96451,2016-09-09 22:00:00.000 +0200,Partly Cloudy,rain,21.522222,21.522222,0.60,10.5294,20,16.1000,0,1015.95,Partly cloudy starting in the morning.
96452,2016-09-09 23:00:00.000 +0200,Partly Cloudy,rain,20.438889,20.438889,0.61,5.8765,39,15.5204,0,1016.16,Partly cloudy starting in the morning.

# Qo. 6 what is mean 'Humidity'?

In [47]:
data.head(2)

,Formatted Date,Summary,Precip Type,Temperature (C),Apparent Temperature (C),Humidity,Wind Speed (km/h),Wind Bearing (degrees),Visibility (km),Loud Cover,Pressure (millibars),weather
0,2006-04-01 00:00:00.000 +0200,Partly Cloudy,rain,9.472222,7.388889,0.89,14.1197,251,15.8263,0,1015.13,Partly cloudy throughout the day.
1,2006-04-01 01:00:00.000 +0200,Partly Cloudy,rain,9.355556,7.227778,0.86,14.2646,259,15.8263,0,1015.63,Partly cloudy throughout the day.

In [42]:
data.Humidity.mean()

0.7348989663358906

# Qo.7 What is the standard deviation of 'pressure' in this data?

In [68]:
data.head(2)

,Formatted Date,Summary,Precip Type,Temperature (C),Apparent Temperature (C),Humidity,Wind Speed (km/h),Wind Bearing (degrees),Visibility (km),Loud Cover,Pressure (millibars),weather
0,2006-04-01 00:00:00.000 +0200,Partly Cloudy,rain,9.472222,7.388889,0.89,14.1197,251,15.8263,0,1015.13,Partly cloudy throughout the day.
1,2006-04-01 01:00:00.000 +0200,Partly Cloudy,rain,9.355556,7.227778,0.86,14.2646,259,15.8263,0,1015.63,Partly cloudy throughout the day.

In [72]:
data['Pressure (millibars)'].std()

116.96990568258147

# Qo.8  What is the variance of 'Apparent Temperature ' in this data?

In [69]:
data.head(2)

,Formatted Date,Summary,Precip Type,Temperature (C),Apparent Temperature (C),Humidity,Wind Speed (km/h),Wind Bearing (degrees),Visibility (km),Loud Cover,Pressure (millibars),weather
0,2006-04-01 00:00:00.000 +0200,Partly Cloudy,rain,9.472222,7.388889,0.89,14.1197,251,15.8263,0,1015.13,Partly cloudy throughout the day.
1,2006-04-01 01:00:00.000 +0200,Partly Cloudy,rain,9.355556,7.227778,0.86,14.2646,259,15.8263,0,1015.63,Partly cloudy throughout the day.

In [73]:
data['Apparent Temperature (C)'].var()

114.4225441304794

# Qo.9 Find all the instance when 'Foggy in the morning.' was recorded?

In [79]:
#value_counts
data.head(2)
data['weather'].value_counts()

Mostly cloudy throughout the day.                                                                     20085
Partly cloudy throughout the day.                                                                      9981
Partly cloudy until night.                                                                             6169
Partly cloudy starting in the morning.                                                                 5184
Foggy in the morning.                                                                                  4201
                                                                                                      ...
Breezy starting in the morning continuing until night.                                                   24
Mostly cloudy throughout the day and breezy starting in the evening continuing until night.              24
Drizzle starting in the evening.                                                                         24
Breezy starting in the afternoon continuing until night and mostly cloudy starting in the evening.       24
Foggy starting overnight continuing until morning and breezy in the afternoon.                           23
Name: weather, Length: 214, dtype: int64

# Qo. 10 find all instance when 'wind speed is above 56 and visibility is less than 45.

In [80]:
data.head(2)

,Formatted Date,Summary,Precip Type,Temperature (C),Apparent Temperature (C),Humidity,Wind Speed (km/h),Wind Bearing (degrees),Visibility (km),Loud Cover,Pressure (millibars),weather
0,2006-04-01 00:00:00.000 +0200,Partly Cloudy,rain,9.472222,7.388889,0.89,14.1197,251,15.8263,0,1015.13,Partly cloudy throughout the day.
1,2006-04-01 01:00:00.000 +0200,Partly Cloudy,rain,9.355556,7.227778,0.86,14.2646,259,15.8263,0,1015.63,Partly cloudy throughout the day.

In [83]:
data[(data['Wind Speed (km/h)']>56) & (data['Visibility (km)']<45)]

,Formatted Date,Summary,Precip Type,Temperature (C),Apparent Temperature (C),Humidity,Wind Speed (km/h),Wind Bearing (degrees),Visibility (km),Loud Cover,Pressure (millibars),weather
12181,2007-01-29 13:00:00.000 +0100,Dangerously Windy and Partly Cloudy,rain,8.944444,3.483333,0.49,63.8526,307,11.4471,0,1009.05,Mostly cloudy throughout the day and windy sta...

# Qo.11 what is the mean value of each column against 'weather'?

In [84]:
data.head(2)

,Formatted Date,Summary,Precip Type,Temperature (C),Apparent Temperature (C),Humidity,Wind Speed (km/h),Wind Bearing (degrees),Visibility (km),Loud Cover,Pressure (millibars),weather
0,2006-04-01 00:00:00.000 +0200,Partly Cloudy,rain,9.472222,7.388889,0.89,14.1197,251,15.8263,0,1015.13,Partly cloudy throughout the day.
1,2006-04-01 01:00:00.000 +0200,Partly Cloudy,rain,9.355556,7.227778,0.86,14.2646,259,15.8263,0,1015.63,Partly cloudy throughout the day.

In [87]:
data.groupby('weather').mean()

,Temperature (C),Apparent Temperature (C),Humidity,Wind Speed (km/h),Wind Bearing (degrees),Visibility (km),Loud Cover,Pressure (millibars)
weather,,,,,,,,
Breezy and foggy starting in the evening.,4.523843,0.485880,0.979583,21.327133,137.833333,6.888117,0.0,991.355417
Breezy and foggy until morning.,-4.869213,-10.947222,0.803750,21.448554,257.166667,7.986942,0.0,1014.138750
Breezy and mostly cloudy overnight.,3.755787,-0.340741,0.733750,19.908992,248.833333,12.492258,0.0,1007.213333
Breezy and partly cloudy in the afternoon.,28.097917,27.488657,0.418333,16.992208,223.541667,11.504792,0.0,1005.110000
Breezy in the morning and foggy in the evening.,0.743750,-5.121528,0.802083,26.870900,27.541667,10.797733,0.0,1013.686250
...,...,...,...,...,...,...,...,...
Partly cloudy until night.,17.675495,17.282404,0.650827,9.637616,198.950397,11.919778,0.0,1011.081989
Rain throughout the day.,10.128241,9.285880,0.892917,11.803312,167.625000,9.109246,0.0,1014.335417
Rain until afternoon.,11.701157,11.328009,0.868333,11.276708,69.000000,0.000000,0.0,1021.991250
Rain until morning.,9.304630,8.253009,0.797083,8.918058,264.958333,10.307354,0.0,1016.951250
Windy in the afternoon.,4.538889,1.004167,0.722917,18.857125,258.416667,7.235608,0.0,341.752917

# Qo. 12 Show all the records where weather condition is 'Foggy in the evening'?

In [88]:
data.head(2)

,Formatted Date,Summary,Precip Type,Temperature (C),Apparent Temperature (C),Humidity,Wind Speed (km/h),Wind Bearing (degrees),Visibility (km),Loud Cover,Pressure (millibars),weather
0,2006-04-01 00:00:00.000 +0200,Partly Cloudy,rain,9.472222,7.388889,0.89,14.1197,251,15.8263,0,1015.13,Partly cloudy throughout the day.
1,2006-04-01 01:00:00.000 +0200,Partly Cloudy,rain,9.355556,7.227778,0.86,14.2646,259,15.8263,0,1015.63,Partly cloudy throughout the day.

In [112]:
data[data['weather']=='Foggy in the evening.']

,Formatted Date,Summary,Precip Type,Temperature (C),Apparent Temperature (C),Humidity,Wind Speed (km/h),Wind Bearing (degrees),Visibility (km),Loud Cover,Pressure (millibars),weather
48,2006-04-11 00:00:00.000 +0200,Overcast,rain,13.772222,13.772222,0.60,17.0982,160,15.8263,0,1007.36,Foggy in the evening.
49,2006-04-11 01:00:00.000 +0200,Overcast,rain,13.283333,13.283333,0.63,14.3612,160,15.8263,0,1007.26,Foggy in the evening.
50,2006-04-11 02:00:00.000 +0200,Overcast,rain,8.633333,5.466667,0.87,22.0409,32,6.6976,0,1005.10,Foggy in the evening.
51,2006-04-11 03:00:00.000 +0200,Overcast,rain,11.250000,11.250000,0.83,11.3344,152,15.8263,0,1007.01,Foggy in the evening.
52,2006-04-11 04:00:00.000 +0200,Overcast,rain,11.183333,11.183333,0.89,11.2056,180,9.9015,0,1006.73,Foggy in the evening.
...,...,...,...,...,...,...,...,...,...,...,...,...
81664,2015-02-04 19:00:00.000 +0100,Overcast,rain,1.111111,-1.283333,0.93,7.5831,20,3.7030,0,1010.25,Foggy in the evening.
81665,2015-02-04 20:00:00.000 +0100,Foggy,rain,1.133333,-1.316667,0.93,7.7602,352,2.9785,0,1011.37,Foggy in the evening.
81666,2015-02-04 21:00:00.000 +0100,Overcast,rain,1.644444,-1.555556,0.92,10.9319,341,3.4615,0,1012.25,Foggy in the evening.
81667,2015-02-04 22:00:00.000 +0100,Overcast,rain,1.566667,-1.544444,0.93,10.4811,358,4.0733,0,1012.65,Foggy in the evening.
81668,2015-02-04 23:00:00.000 +0100,Foggy,rain,1.622222,-2.166667,0.96,13.7333,0,1.4490,0,1012.97,Foggy in the evening.

# Qo.13 Find all the instances when 'Foggy in the morning'  or 'visibility is above 9.

In [113]:
data.head(2)

,Formatted Date,Summary,Precip Type,Temperature (C),Apparent Temperature (C),Humidity,Wind Speed (km/h),Wind Bearing (degrees),Visibility (km),Loud Cover,Pressure (millibars),weather
0,2006-04-01 00:00:00.000 +0200,Partly Cloudy,rain,9.472222,7.388889,0.89,14.1197,251,15.8263,0,1015.13,Partly cloudy throughout the day.
1,2006-04-01 01:00:00.000 +0200,Partly Cloudy,rain,9.355556,7.227778,0.86,14.2646,259,15.8263,0,1015.63,Partly cloudy throughout the day.

In [117]:
data[(data['weather']=='Foggy in the morning.') | (data['Visibility (km)']>9)]

,Formatted Date,Summary,Precip Type,Temperature (C),Apparent Temperature (C),Humidity,Wind Speed (km/h),Wind Bearing (degrees),Visibility (km),Loud Cover,Pressure (millibars),weather
0,2006-04-01 00:00:00.000 +0200,Partly Cloudy,rain,9.472222,7.388889,0.89,14.1197,251,15.8263,0,1015.13,Partly cloudy throughout the day.
1,2006-04-01 01:00:00.000 +0200,Partly Cloudy,rain,9.355556,7.227778,0.86,14.2646,259,15.8263,0,1015.63,Partly cloudy throughout the day.
2,2006-04-01 02:00:00.000 +0200,Mostly Cloudy,rain,9.377778,9.377778,0.89,3.9284,204,14.9569,0,1015.94,Partly cloudy throughout the day.
3,2006-04-01 03:00:00.000 +0200,Partly Cloudy,rain,8.288889,5.944444,0.83,14.1036,269,15.8263,0,1016.41,Partly cloudy throughout the day.
4,2006-04-01 04:00:00.000 +0200,Mostly Cloudy,rain,8.755556,6.977778,0.83,11.0446,259,15.8263,0,1016.51,Partly cloudy throughout the day.
...,...,...,...,...,...,...,...,...,...,...,...,...
96448,2016-09-09 19:00:00.000 +0200,Partly Cloudy,rain,26.016667,26.016667,0.43,10.9963,31,16.1000,0,1014.36,Partly cloudy starting in the morning.
96449,2016-09-09 20:00:00.000 +0200,Partly Cloudy,rain,24.583333,24.583333,0.48,10.0947,20,15.5526,0,1015.16,Partly cloudy starting in the morning.
96450,2016-09-09 21:00:00.000 +0200,Partly Cloudy,rain,22.038889,22.038889,0.56,8.9838,30,16.1000,0,1015.66,Partly cloudy starting in the morning.
96451,2016-09-09 22:00:00.000 +0200,Partly Cloudy,rain,21.522222,21.522222,0.60,10.5294,20,16.1000,0,1015.95,Partly cloudy starting in the morning.
96452,2016-09-09 23:00:00.000 +0200,Partly Cloudy,rain,20.438889,20.438889,0.61,5.8765,39,15.5204,0,1016.16,Partly cloudy starting in the morning.